// <auto-generated />
using System;
using BeybladeRecordSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeybladeRecordSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820033301_AddQuickBattleInvitationFlow")]
    partial class AddQuickBattleInvitationFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineupSequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PendingLineupEditRequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlayerAEditRequestUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerAId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlayerALineupConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlayerBEditRequestUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerBId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PlayerBLineupConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreToWin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SideADesignation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SideAScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SideBScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TournamentMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("VoidSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VoidedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VoidedTournamentMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinningPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinningSide")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlayerAId");

                    b.HasIndex("PlayerBId");

                    b.HasIndex("TournamentMatchId")
                        .IsUnique();

                    b.HasIndex("VoidedByUserId");

                    b.HasIndex("VoidedTournamentMatchId");

                    b.ToTable("Battles", t =>
                        {
                            t.HasCheckConstraint("CK_Battle_DifferentPlayers", "PlayerAId IS NULL OR PlayerBId IS NULL OR PlayerAId <> PlayerBId");

                            t.HasCheckConstraint("CK_Battle_LineupSequenceNo", "LineupSequenceNo > 0");

                            t.HasCheckConstraint("CK_Battle_ScoreToWin", "ScoreToWin > 0");

                            t.HasCheckConstraint("CK_Battle_Scores", "SideAScore >= 0 AND SideBScore >= 0");

                            t.HasCheckConstraint("CK_Battle_SourceMatch", "(SourceType = 0 AND Status <> 7 AND TournamentMatchId IS NULL AND VoidedTournamentMatchId IS NULL) OR (SourceType IN (1, 2) AND ((Status <> 7 AND TournamentMatchId IS NOT NULL AND VoidedTournamentMatchId IS NULL) OR (Status = 7 AND TournamentMatchId IS NULL AND VoidedTournamentMatchId IS NOT NULL AND VoidedByUserId IS NOT NULL AND VoidedAtUtc IS NOT NULL AND LENGTH(TRIM(VoidReason)) > 0 AND VoidSnapshot IS NOT NULL)))");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerABeybladeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerABeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerADisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerBBeybladeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerBBeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerBDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerBId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerABeybladeId");

                    b.HasIndex("PlayerAId");

                    b.HasIndex("PlayerBBeybladeId");

                    b.HasIndex("PlayerBId");

                    b.HasIndex("BattleId", "SequenceNo", "PositionNo")
                        .IsUnique();

                    b.ToTable("BattleLineups");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineupSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeybladeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BeybladeNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeybladeId");

                    b.HasIndex("UserId");

                    b.HasIndex("BattleId", "SequenceNo", "BeybladeId")
                        .IsUnique();

                    b.HasIndex("BattleId", "SequenceNo", "UserId", "PositionNo")
                        .IsUnique();

                    b.ToTable("BattleLineupSelections", t =>
                        {
                            t.HasCheckConstraint("CK_BattleLineupSelection_PositionNo", "PositionNo > 0");

                            t.HasCheckConstraint("CK_BattleLineupSelection_SequenceNo", "SequenceNo > 0");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerABeybladeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerABeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerADisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerBBeybladeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerBBeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerBDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerBId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineupId");

                    b.HasIndex("PlayerAId");

                    b.HasIndex("PlayerBId");

                    b.HasIndex("BattleId", "RoundNo")
                        .IsUnique();

                    b.ToTable("BattleRounds");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActorPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleRoundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvalidationReason")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEffective")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BattleRoundId", "EventSequence")
                        .IsUnique();

                    b.ToTable("BattleRoundEvents");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleRoundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewBattleSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewEffectiveEventSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousBattleSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousEffectiveEventSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BattleRoundId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("BattleRoundRevisions");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleTeamOrderSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("TournamentEntryId");

                    b.HasIndex("UserId");

                    b.HasIndex("BattleId", "SequenceNo", "TournamentEntryId", "PositionNo")
                        .IsUnique();

                    b.HasIndex("BattleId", "SequenceNo", "TournamentEntryId", "UserId")
                        .IsUnique();

                    b.ToTable("BattleTeamOrderSelections", t =>
                        {
                            t.HasCheckConstraint("CK_BattleTeamOrderSelection_PositionNo", "PositionNo > 0");

                            t.HasCheckConstraint("CK_BattleTeamOrderSelection_SequenceNo", "SequenceNo > 0");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Beyblade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Beyblades");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.QuickBattleInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("InviteeUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InviterUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("InviteeUserId", "CreatedAtUtc");

                    b.HasIndex("InviterUserId", "InviteeUserId")
                        .IsUnique();

                    b.ToTable("QuickBattleInvitations");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeybladesPerPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RegistrationClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistrationMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegistrationStage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RuleSet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RulesSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreToWin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetEntryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerUserId", "UpdatedAtUtc");

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.ToTable("Tournaments", t =>
                        {
                            t.HasCheckConstraint("CK_Tournament_BeybladesPerPlayer", "BeybladesPerPlayer > 0");

                            t.HasCheckConstraint("CK_Tournament_ScoreToWin", "ScoreToWin > 0");

                            t.HasCheckConstraint("CK_Tournament_TargetEntryCount", "TargetEntryCount BETWEEN 2 AND 512");

                            t.HasCheckConstraint("CK_Tournament_TeamSize", "(Mode = 0 AND TeamSize IS NULL) OR (Mode = 1 AND TeamSize IN (2, 3))");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(192)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndividualUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RegisteredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SchedulePosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WithdrawnAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IndividualUserId");

                    b.HasIndex("TournamentId", "IndividualUserId")
                        .IsUnique();

                    b.HasIndex("TournamentId", "RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("TournamentId", "SchedulePosition")
                        .IsUnique();

                    b.ToTable("TournamentEntries");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntryMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TournamentEntryId", "MemberOrder")
                        .IsUnique();

                    b.HasIndex("TournamentId", "UserId")
                        .IsUnique();

                    b.ToTable("TournamentEntryMembers", t =>
                        {
                            t.HasCheckConstraint("CK_TournamentEntryMember_MemberOrder", "MemberOrder > 0");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InvalidatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvitedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TournamentEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("TournamentEntryId");

                    b.HasIndex("TournamentId", "Status");

                    b.HasIndex("InvitedUserId", "Status", "CreatedAtUtc");

                    b.ToTable("TournamentInvitations");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bracket")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBye")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResetFinal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeedQualifier")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoserEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoserToMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SideAEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SideASourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SideASourceReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SideBEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SideBSourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SideBSourceReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("WinnerEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerToMatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoserEntryId");

                    b.HasIndex("LoserToMatchId");

                    b.HasIndex("SideAEntryId");

                    b.HasIndex("SideBEntryId");

                    b.HasIndex("WinnerEntryId");

                    b.HasIndex("WinnerToMatchId");

                    b.HasIndex("TournamentId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("TournamentId", "Status");

                    b.HasIndex("TournamentId", "Bracket", "RoundNumber", "MatchNumber")
                        .IsUnique();

                    b.ToTable("TournamentMatches", t =>
                        {
                            t.HasCheckConstraint("CK_TournamentMatch_ByeSide", "IsBye = 0 OR SideBSourceReferenceId IS NULL");

                            t.HasCheckConstraint("CK_TournamentMatch_MatchNumber", "MatchNumber > 0");

                            t.HasCheckConstraint("CK_TournamentMatch_RoundNumber", "RoundNumber > 0");

                            t.HasCheckConstraint("CK_TournamentMatch_SequenceNumber", "SequenceNumber > 0");

                            t.HasCheckConstraint("CK_TournamentMatch_SideAReference", "SideASourceReferenceId > 0");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatchParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMatchRepresentative")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LineupConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LineupConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("TournamentEntryId");

                    b.HasIndex("UserId");

                    b.HasIndex("TournamentMatchId", "UserId")
                        .IsUnique();

                    b.HasIndex("TournamentMatchId", "TournamentEntryId", "UserId")
                        .IsUnique();

                    b.ToTable("TournamentMatchParticipants");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Battle", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerA")
                        .WithMany()
                        .HasForeignKey("PlayerAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerB")
                        .WithMany()
                        .HasForeignKey("PlayerBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "TournamentMatch")
                        .WithOne("Battle")
                        .HasForeignKey("BeybladeRecordSystem.Domain.Entities.Battle", "TournamentMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "VoidedByUser")
                        .WithMany()
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "VoidedTournamentMatch")
                        .WithMany("VoidedBattles")
                        .HasForeignKey("VoidedTournamentMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("PlayerA");

                    b.Navigation("PlayerB");

                    b.Navigation("TournamentMatch");

                    b.Navigation("VoidedByUser");

                    b.Navigation("VoidedTournamentMatch");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineup", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("Lineups")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Beyblade", "PlayerABeyblade")
                        .WithMany()
                        .HasForeignKey("PlayerABeybladeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerA")
                        .WithMany()
                        .HasForeignKey("PlayerAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Beyblade", "PlayerBBeyblade")
                        .WithMany()
                        .HasForeignKey("PlayerBBeybladeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerB")
                        .WithMany()
                        .HasForeignKey("PlayerBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Battle");

                    b.Navigation("PlayerA");

                    b.Navigation("PlayerABeyblade");

                    b.Navigation("PlayerB");

                    b.Navigation("PlayerBBeyblade");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineupSelection", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("LineupSelections")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Beyblade", "Beyblade")
                        .WithMany()
                        .HasForeignKey("BeybladeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("Beyblade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRound", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("Rounds")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BattleLineup", "Lineup")
                        .WithMany()
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerA")
                        .WithMany()
                        .HasForeignKey("PlayerAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerB")
                        .WithMany()
                        .HasForeignKey("PlayerBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Battle");

                    b.Navigation("Lineup");

                    b.Navigation("PlayerA");

                    b.Navigation("PlayerB");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundEvent", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BattleRound", "BattleRound")
                        .WithMany("Events")
                        .HasForeignKey("BattleRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BattleRound");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundRevision", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BattleRound", "BattleRound")
                        .WithMany("Revisions")
                        .HasForeignKey("BattleRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BattleRound");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleTeamOrderSelection", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("TeamOrderSelections")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "TournamentEntry")
                        .WithMany()
                        .HasForeignKey("TournamentEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("SubmittedByUser");

                    b.Navigation("TournamentEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Beyblade", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany("Beyblades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.QuickBattleInvitation", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "InviteeUser")
                        .WithMany()
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "InviterUser")
                        .WithMany()
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InviteeUser");

                    b.Navigation("InviterUser");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "OrganizerUser")
                        .WithMany()
                        .HasForeignKey("OrganizerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganizerUser");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntry", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "IndividualUser")
                        .WithMany()
                        .HasForeignKey("IndividualUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Entries")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualUser");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntryMember", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "TournamentEntry")
                        .WithMany("Members")
                        .HasForeignKey("TournamentEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("TournamentEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentInvitation", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "TournamentEntry")
                        .WithMany()
                        .HasForeignKey("TournamentEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Invitations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");

                    b.Navigation("Tournament");

                    b.Navigation("TournamentEntry");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatch", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "LoserEntry")
                        .WithMany()
                        .HasForeignKey("LoserEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "LoserToMatch")
                        .WithMany()
                        .HasForeignKey("LoserToMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "SideAEntry")
                        .WithMany()
                        .HasForeignKey("SideAEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "SideBEntry")
                        .WithMany()
                        .HasForeignKey("SideBEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "WinnerEntry")
                        .WithMany()
                        .HasForeignKey("WinnerEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "WinnerToMatch")
                        .WithMany()
                        .HasForeignKey("WinnerToMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoserEntry");

                    b.Navigation("LoserToMatch");

                    b.Navigation("SideAEntry");

                    b.Navigation("SideBEntry");

                    b.Navigation("Tournament");

                    b.Navigation("WinnerEntry");

                    b.Navigation("WinnerToMatch");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatchParticipant", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "TournamentEntry")
                        .WithMany()
                        .HasForeignKey("TournamentEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "TournamentMatch")
                        .WithMany("Participants")
                        .HasForeignKey("TournamentMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TournamentEntry");

                    b.Navigation("TournamentMatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Battle", b =>
                {
                    b.Navigation("LineupSelections");

                    b.Navigation("Lineups");

                    b.Navigation("Rounds");

                    b.Navigation("TeamOrderSelections");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRound", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Invitations");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntry", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatch", b =>
                {
                    b.Navigation("Battle");

                    b.Navigation("Participants");

                    b.Navigation("VoidedBattles");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Beyblades");
                });
#pragma warning restore 612, 618
        }
    }
}
