// <auto-generated />
using System;
using BeybladeRecordSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeybladeRecordSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808152245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerAScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerBId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerBScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("WinningPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlayerAId");

                    b.HasIndex("PlayerBId");

                    b.ToTable("Battles", t =>
                        {
                            t.HasCheckConstraint("CK_Battle_DifferentPlayers", "PlayerAId <> PlayerBId");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerABeybladeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerABeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerBBeybladeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerBBeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerABeybladeId");

                    b.HasIndex("PlayerBBeybladeId");

                    b.HasIndex("BattleId", "SequenceNo", "PositionNo")
                        .IsUnique();

                    b.ToTable("BattleLineups");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LineupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerABeybladeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerABeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerBBeybladeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerBBeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineupId");

                    b.HasIndex("BattleId", "RoundNo")
                        .IsUnique();

                    b.ToTable("BattleRounds");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActorPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleRoundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventSequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEffective")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResultType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScoreAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BattleRoundId", "EventSequence")
                        .IsUnique();

                    b.ToTable("BattleRoundEvents");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleRoundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewEffectiveEventSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousEffectiveEventSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BattleRoundId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("BattleRoundRevisions");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Beyblade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Beyblades");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Battle", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerA")
                        .WithMany()
                        .HasForeignKey("PlayerAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerB")
                        .WithMany()
                        .HasForeignKey("PlayerBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("PlayerA");

                    b.Navigation("PlayerB");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineup", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("Lineups")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Beyblade", "PlayerABeyblade")
                        .WithMany()
                        .HasForeignKey("PlayerABeybladeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Beyblade", "PlayerBBeyblade")
                        .WithMany()
                        .HasForeignKey("PlayerBBeybladeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("PlayerABeyblade");

                    b.Navigation("PlayerBBeyblade");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRound", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("Rounds")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BattleLineup", "Lineup")
                        .WithMany()
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("Lineup");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundEvent", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BattleRound", "BattleRound")
                        .WithMany("Events")
                        .HasForeignKey("BattleRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BattleRound");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundRevision", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BattleRound", "BattleRound")
                        .WithMany("Revisions")
                        .HasForeignKey("BattleRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BattleRound");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Beyblade", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany("Beyblades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Battle", b =>
                {
                    b.Navigation("Lineups");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRound", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Beyblades");
                });
#pragma warning restore 612, 618
        }
    }
}
