// <auto-generated />
using System;
using BeybladeRecordSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeybladeRecordSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Battle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("LineupSequenceNo")
                        .HasColumnType("integer");

                    b.Property<int?>("PendingLineupEditRequestedByUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("PlayerAEditRequestUsed")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlayerAId")
                        .HasColumnType("integer");

                    b.Property<bool>("PlayerALineupConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("PlayerBEditRequestUsed")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlayerBId")
                        .HasColumnType("integer");

                    b.Property<bool>("PlayerBLineupConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("ScoreToWin")
                        .HasColumnType("integer");

                    b.Property<int?>("SideADesignation")
                        .HasColumnType("integer");

                    b.Property<int>("SideAScore")
                        .HasColumnType("integer");

                    b.Property<int>("SideBScore")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TournamentMatchId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("VoidSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VoidedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("VoidedTournamentMatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinningPlayerId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinningSide")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlayerAId");

                    b.HasIndex("PlayerBId");

                    b.HasIndex("TournamentMatchId")
                        .IsUnique();

                    b.HasIndex("VoidedByUserId");

                    b.HasIndex("VoidedTournamentMatchId");

                    b.ToTable("Battles", t =>
                        {
                            t.HasCheckConstraint("CK_Battle_DifferentPlayers", "\"PlayerAId\" IS NULL OR \"PlayerBId\" IS NULL OR \"PlayerAId\" <> \"PlayerBId\"");

                            t.HasCheckConstraint("CK_Battle_LineupSequenceNo", "\"LineupSequenceNo\" > 0");

                            t.HasCheckConstraint("CK_Battle_ScoreToWin", "\"ScoreToWin\" > 0");

                            t.HasCheckConstraint("CK_Battle_Scores", "\"SideAScore\" >= 0 AND \"SideBScore\" >= 0");

                            t.HasCheckConstraint("CK_Battle_SourceMatch", "(\"SourceType\" = 0 AND \"Status\" <> 7 AND \"TournamentMatchId\" IS NULL AND \"VoidedTournamentMatchId\" IS NULL) OR (\"SourceType\" IN (1, 2) AND ((\"Status\" <> 7 AND \"TournamentMatchId\" IS NOT NULL AND \"VoidedTournamentMatchId\" IS NULL) OR (\"Status\" = 7 AND \"TournamentMatchId\" IS NULL AND \"VoidedTournamentMatchId\" IS NOT NULL AND \"VoidedByUserId\" IS NOT NULL AND \"VoidedAtUtc\" IS NOT NULL AND LENGTH(TRIM(\"VoidReason\")) > 0 AND \"VoidSnapshot\" IS NOT NULL)))");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerABeybladeId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerABeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlayerAConfigurationId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerADisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PlayerAId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerBBeybladeId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerBBeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlayerBConfigurationId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerBDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PlayerBId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionNo")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerABeybladeId");

                    b.HasIndex("PlayerAId");

                    b.HasIndex("PlayerBBeybladeId");

                    b.HasIndex("PlayerBId");

                    b.HasIndex("PlayerAConfigurationId", "PlayerABeybladeId");

                    b.HasIndex("PlayerBConfigurationId", "PlayerBBeybladeId");

                    b.HasIndex("BattleId", "SequenceNo", "PositionNo")
                        .IsUnique();

                    b.ToTable("BattleLineups");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineupSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("integer");

                    b.Property<int?>("BeybladeConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int>("BeybladeId")
                        .HasColumnType("integer");

                    b.Property<string>("BeybladeNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(520)
                        .HasColumnType("character varying(520)");

                    b.Property<string>("PlayerDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PositionNo")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeybladeId");

                    b.HasIndex("UserId");

                    b.HasIndex("BeybladeConfigurationId", "BeybladeId");

                    b.HasIndex("BattleId", "SequenceNo", "BeybladeId")
                        .IsUnique();

                    b.HasIndex("BattleId", "SequenceNo", "UserId", "PositionNo")
                        .IsUnique();

                    b.ToTable("BattleLineupSelections", t =>
                        {
                            t.HasCheckConstraint("CK_BattleLineupSelection_PositionNo", "\"PositionNo\" > 0");

                            t.HasCheckConstraint("CK_BattleLineupSelection_SequenceNo", "\"SequenceNo\" > 0");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineupId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerABeybladeId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerABeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerADisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PlayerAId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerBBeybladeId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerBBeybladeNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerBDisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PlayerBId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionNo")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNo")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LineupId");

                    b.HasIndex("PlayerAId");

                    b.HasIndex("PlayerBId");

                    b.HasIndex("BattleId", "RoundNo")
                        .IsUnique();

                    b.ToTable("BattleRounds");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("BattleRoundId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventSequence")
                        .HasColumnType("integer");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<int?>("InvalidationReason")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEffective")
                        .HasColumnType("boolean");

                    b.Property<int?>("ResultType")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreAwarded")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BattleRoundId", "EventSequence")
                        .IsUnique();

                    b.ToTable("BattleRoundEvents");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleRoundId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("NewBattleSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewEffectiveEventSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousBattleSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousEffectiveEventSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BattleRoundId");

                    b.HasIndex("ChangedByUserId");

                    b.ToTable("BattleRoundRevisions");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleTeamOrderSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionNo")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("TournamentEntryId");

                    b.HasIndex("UserId");

                    b.HasIndex("BattleId", "SequenceNo", "TournamentEntryId", "PositionNo")
                        .IsUnique();

                    b.HasIndex("BattleId", "SequenceNo", "TournamentEntryId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_BattleTeamOrderSelections_BattleId_SequenceNo_TournamentEn~1");

                    b.ToTable("BattleTeamOrderSelections", t =>
                        {
                            t.HasCheckConstraint("CK_BattleTeamOrderSelection_PositionNo", "\"PositionNo\" > 0");

                            t.HasCheckConstraint("CK_BattleTeamOrderSelection_SequenceNo", "\"SequenceNo\" > 0");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Beyblade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpperName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.HasIndex("UserId", "UpperName")
                        .IsUnique()
                        .HasFilter("\"UpperName\" IS NOT NULL AND NOT \"IsDeleted\"");

                    b.ToTable("Beyblades");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BeybladeConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeybladeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartsKey")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BeybladeId", "PartsKey")
                        .IsUnique();

                    b.HasIndex("BeybladeId", "VersionNo")
                        .IsUnique();

                    b.ToTable("BeybladeConfigurations", t =>
                        {
                            t.HasCheckConstraint("CK_Configuration_Version", "\"VersionNo\" > 0");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BeybladeConfigurationPart", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<string>("PartNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ConfigurationId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("BeybladeConfigurationParts");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IntegratesRatchet")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Name")
                        .IsUnique();

                    b.ToTable("Parts", t =>
                        {
                            t.HasCheckConstraint("CK_Part_Category", "\"Category\" BETWEEN 0 AND 7");

                            t.HasCheckConstraint("CK_Part_IntegratesRatchet", "NOT \"IntegratesRatchet\" OR \"Category\" IN (0, 2)");

                            t.HasCheckConstraint("CK_Part_Name", "LENGTH(TRIM(\"Name\")) > 0 AND \"Name\" = TRIM(\"Name\")");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.PartSeries", b =>
                {
                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.HasKey("PartId", "Series");

                    b.ToTable("PartSeries", t =>
                        {
                            t.HasCheckConstraint("CK_PartSeries_Series", "\"Series\" BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.QuickBattleInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InviteeUserId")
                        .HasColumnType("integer");

                    b.Property<int>("InviterUserId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("InviteeUserId", "CreatedAtUtc");

                    b.HasIndex("InviterUserId", "InviteeUserId")
                        .IsUnique();

                    b.ToTable("QuickBattleInvitations");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeybladesPerPlayer")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OrganizerUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RegistrationClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegistrationMode")
                        .HasColumnType("integer");

                    b.Property<int>("RegistrationStage")
                        .HasColumnType("integer");

                    b.Property<int>("RuleSet")
                        .HasColumnType("integer");

                    b.Property<string>("RulesSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScoreToWin")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetEntryCount")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerUserId", "UpdatedAtUtc");

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.ToTable("Tournaments", t =>
                        {
                            t.HasCheckConstraint("CK_Tournament_BeybladesPerPlayer", "\"BeybladesPerPlayer\" > 0");

                            t.HasCheckConstraint("CK_Tournament_ScoreToWin", "\"ScoreToWin\" > 0");

                            t.HasCheckConstraint("CK_Tournament_TargetEntryCount", "\"TargetEntryCount\" BETWEEN 2 AND 512");

                            t.HasCheckConstraint("CK_Tournament_TeamSize", "(\"Mode\" = 0 AND \"TeamSize\" IS NULL) OR (\"Mode\" = 1 AND \"TeamSize\" IN (2, 3))");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(192)
                        .HasColumnType("character varying(192)");

                    b.Property<int?>("IndividualUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("SchedulePosition")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WithdrawnAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IndividualUserId");

                    b.HasIndex("TournamentId", "IndividualUserId")
                        .IsUnique();

                    b.HasIndex("TournamentId", "RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("TournamentId", "SchedulePosition")
                        .IsUnique();

                    b.ToTable("TournamentEntries");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntryMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemberOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TournamentEntryId", "MemberOrder")
                        .IsUnique();

                    b.HasIndex("TournamentId", "UserId")
                        .IsUnique();

                    b.ToTable("TournamentEntryMembers", t =>
                        {
                            t.HasCheckConstraint("CK_TournamentEntryMember_MemberOrder", "\"MemberOrder\" > 0");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InvalidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("InvitedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TournamentEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("TournamentEntryId");

                    b.HasIndex("TournamentId", "Status");

                    b.HasIndex("InvitedUserId", "Status", "CreatedAtUtc");

                    b.ToTable("TournamentInvitations");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bracket")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBye")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResetFinal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeedQualifier")
                        .HasColumnType("boolean");

                    b.Property<int?>("LoserEntryId")
                        .HasColumnType("integer");

                    b.Property<int?>("LoserToMatchId")
                        .HasColumnType("integer");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("SideAEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("SideASourceKind")
                        .HasColumnType("integer");

                    b.Property<int>("SideASourceReferenceId")
                        .HasColumnType("integer");

                    b.Property<int?>("SideBEntryId")
                        .HasColumnType("integer");

                    b.Property<int?>("SideBSourceKind")
                        .HasColumnType("integer");

                    b.Property<int?>("SideBSourceReferenceId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("WinnerEntryId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerToMatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoserEntryId");

                    b.HasIndex("LoserToMatchId");

                    b.HasIndex("SideAEntryId");

                    b.HasIndex("SideBEntryId");

                    b.HasIndex("WinnerEntryId");

                    b.HasIndex("WinnerToMatchId");

                    b.HasIndex("TournamentId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("TournamentId", "Status");

                    b.HasIndex("TournamentId", "Bracket", "RoundNumber", "MatchNumber")
                        .IsUnique();

                    b.ToTable("TournamentMatches", t =>
                        {
                            t.HasCheckConstraint("CK_TournamentMatch_ByeSide", "NOT \"IsBye\" OR \"SideBSourceReferenceId\" IS NULL");

                            t.HasCheckConstraint("CK_TournamentMatch_MatchNumber", "\"MatchNumber\" > 0");

                            t.HasCheckConstraint("CK_TournamentMatch_RoundNumber", "\"RoundNumber\" > 0");

                            t.HasCheckConstraint("CK_TournamentMatch_SequenceNumber", "\"SequenceNumber\" > 0");

                            t.HasCheckConstraint("CK_TournamentMatch_SideAReference", "\"SideASourceReferenceId\" > 0");
                        });
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatchParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMatchRepresentative")
                        .HasColumnType("boolean");

                    b.Property<bool>("LineupConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LineupConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NotifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentMatchId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("TournamentEntryId");

                    b.HasIndex("UserId");

                    b.HasIndex("TournamentMatchId", "UserId")
                        .IsUnique();

                    b.HasIndex("TournamentMatchId", "TournamentEntryId", "UserId")
                        .IsUnique();

                    b.ToTable("TournamentMatchParticipants");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedAccount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAccount")
                        .IsUnique();

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DedupeKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.HasIndex("UserId", "DedupeKey")
                        .IsUnique()
                        .HasFilter("\"ResolvedAtUtc\" IS NULL AND \"DedupeKey\" IS NOT NULL");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Battle", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerA")
                        .WithMany()
                        .HasForeignKey("PlayerAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerB")
                        .WithMany()
                        .HasForeignKey("PlayerBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "TournamentMatch")
                        .WithOne("Battle")
                        .HasForeignKey("BeybladeRecordSystem.Domain.Entities.Battle", "TournamentMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "VoidedByUser")
                        .WithMany()
                        .HasForeignKey("VoidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "VoidedTournamentMatch")
                        .WithMany("VoidedBattles")
                        .HasForeignKey("VoidedTournamentMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("PlayerA");

                    b.Navigation("PlayerB");

                    b.Navigation("TournamentMatch");

                    b.Navigation("VoidedByUser");

                    b.Navigation("VoidedTournamentMatch");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineup", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("Lineups")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Beyblade", "PlayerABeyblade")
                        .WithMany()
                        .HasForeignKey("PlayerABeybladeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerA")
                        .WithMany()
                        .HasForeignKey("PlayerAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Beyblade", "PlayerBBeyblade")
                        .WithMany()
                        .HasForeignKey("PlayerBBeybladeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerB")
                        .WithMany()
                        .HasForeignKey("PlayerBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BeybladeConfiguration", "PlayerAConfiguration")
                        .WithMany()
                        .HasForeignKey("PlayerAConfigurationId", "PlayerABeybladeId")
                        .HasPrincipalKey("Id", "BeybladeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BeybladeConfiguration", "PlayerBConfiguration")
                        .WithMany()
                        .HasForeignKey("PlayerBConfigurationId", "PlayerBBeybladeId")
                        .HasPrincipalKey("Id", "BeybladeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Battle");

                    b.Navigation("PlayerA");

                    b.Navigation("PlayerABeyblade");

                    b.Navigation("PlayerAConfiguration");

                    b.Navigation("PlayerB");

                    b.Navigation("PlayerBBeyblade");

                    b.Navigation("PlayerBConfiguration");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleLineupSelection", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("LineupSelections")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Beyblade", "Beyblade")
                        .WithMany()
                        .HasForeignKey("BeybladeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BeybladeConfiguration", "BeybladeConfiguration")
                        .WithMany()
                        .HasForeignKey("BeybladeConfigurationId", "BeybladeId")
                        .HasPrincipalKey("Id", "BeybladeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Battle");

                    b.Navigation("Beyblade");

                    b.Navigation("BeybladeConfiguration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRound", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("Rounds")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BattleLineup", "Lineup")
                        .WithMany()
                        .HasForeignKey("LineupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerA")
                        .WithMany()
                        .HasForeignKey("PlayerAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "PlayerB")
                        .WithMany()
                        .HasForeignKey("PlayerBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Battle");

                    b.Navigation("Lineup");

                    b.Navigation("PlayerA");

                    b.Navigation("PlayerB");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundEvent", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BattleRound", "BattleRound")
                        .WithMany("Events")
                        .HasForeignKey("BattleRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BattleRound");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRoundRevision", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BattleRound", "BattleRound")
                        .WithMany("Revisions")
                        .HasForeignKey("BattleRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BattleRound");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleTeamOrderSelection", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Battle", "Battle")
                        .WithMany("TeamOrderSelections")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "TournamentEntry")
                        .WithMany()
                        .HasForeignKey("TournamentEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Battle");

                    b.Navigation("SubmittedByUser");

                    b.Navigation("TournamentEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Beyblade", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany("Beyblades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BeybladeConfiguration", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Beyblade", "Beyblade")
                        .WithMany("Configurations")
                        .HasForeignKey("BeybladeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beyblade");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BeybladeConfigurationPart", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.BeybladeConfiguration", "Configuration")
                        .WithMany("Parts")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.PartSeries", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Part", "Part")
                        .WithMany("Series")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.QuickBattleInvitation", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "InviteeUser")
                        .WithMany()
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "InviterUser")
                        .WithMany()
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InviteeUser");

                    b.Navigation("InviterUser");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "OrganizerUser")
                        .WithMany()
                        .HasForeignKey("OrganizerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganizerUser");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntry", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "IndividualUser")
                        .WithMany()
                        .HasForeignKey("IndividualUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Entries")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndividualUser");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntryMember", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "TournamentEntry")
                        .WithMany("Members")
                        .HasForeignKey("TournamentEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("TournamentEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentInvitation", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "InvitedUser")
                        .WithMany()
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "TournamentEntry")
                        .WithMany()
                        .HasForeignKey("TournamentEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Invitations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("InvitedUser");

                    b.Navigation("Tournament");

                    b.Navigation("TournamentEntry");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatch", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "LoserEntry")
                        .WithMany()
                        .HasForeignKey("LoserEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "LoserToMatch")
                        .WithMany()
                        .HasForeignKey("LoserToMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "SideAEntry")
                        .WithMany()
                        .HasForeignKey("SideAEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "SideBEntry")
                        .WithMany()
                        .HasForeignKey("SideBEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "WinnerEntry")
                        .WithMany()
                        .HasForeignKey("WinnerEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "WinnerToMatch")
                        .WithMany()
                        .HasForeignKey("WinnerToMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoserEntry");

                    b.Navigation("LoserToMatch");

                    b.Navigation("SideAEntry");

                    b.Navigation("SideBEntry");

                    b.Navigation("Tournament");

                    b.Navigation("WinnerEntry");

                    b.Navigation("WinnerToMatch");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatchParticipant", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentEntry", "TournamentEntry")
                        .WithMany()
                        .HasForeignKey("TournamentEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.TournamentMatch", "TournamentMatch")
                        .WithMany("Participants")
                        .HasForeignKey("TournamentMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TournamentEntry");

                    b.Navigation("TournamentMatch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("BeybladeRecordSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Battle", b =>
                {
                    b.Navigation("LineupSelections");

                    b.Navigation("Lineups");

                    b.Navigation("Rounds");

                    b.Navigation("TeamOrderSelections");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BattleRound", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Beyblade", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.BeybladeConfiguration", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Part", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Invitations");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentEntry", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.TournamentMatch", b =>
                {
                    b.Navigation("Battle");

                    b.Navigation("Participants");

                    b.Navigation("VoidedBattles");
                });

            modelBuilder.Entity("BeybladeRecordSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Beyblades");
                });
#pragma warning restore 612, 618
        }
    }
}
