using BeybladeRecordSystem.Data;
using BeybladeRecordSystem.Domain.Entities;
using BeybladeRecordSystem.Domain.Enums;
using BeybladeRecordSystem.Domain.Tournaments;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace BeybladeRecordSystem.Tests;

public class TournamentPersistenceTests
{
    [Fact]
    public void CurrentPostgreSqlModel_HasNoPendingMigrationChanges()
    {
        using var context = CreatePostgreSqlContext();

        Assert.False(context.Database.HasPendingModelChanges());
    }

    [Fact]
    public void PostgreSqlInitialMigration_ContainsTheCompleteSchema()
    {
        using var context = CreatePostgreSqlContext();
        var script = context.GetService<IMigrator>().GenerateScript();

        Assert.Contains("CREATE TABLE \"Battles\"", script);
        Assert.Contains("CREATE TABLE \"Tournaments\"", script);
        Assert.Contains("CREATE TABLE \"TournamentMatchParticipants\"", script);
        Assert.Contains("CREATE TABLE \"QuickBattleInvitations\"", script);
        Assert.Contains("timestamp with time zone", script);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", script);
        Assert.DoesNotContain("Sqlite:", script, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task DuplicateRegistrationNumberWithinTournament_IsRejected()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();
        await using var context = CreateContext(connection);
        await context.Database.EnsureCreatedAsync();

        var organizer = CreateUser("organizer");
        var tournament = CreateIndividualTournament(organizer);
        context.AddRange(organizer, tournament);
        await context.SaveChangesAsync();

        context.TournamentEntries.AddRange(
            CreateEntry(tournament.Id, "A-001", "Player 1"),
            CreateEntry(tournament.Id, "A-001", "Player 2"));

        await Assert.ThrowsAsync<DbUpdateException>(() => context.SaveChangesAsync());
    }

    [Fact]
    public async Task SamePlayerCannotBelongToTwoEntriesInOneTournament()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();
        await using var context = CreateContext(connection);
        await context.Database.EnsureCreatedAsync();

        var organizer = CreateUser("organizer");
        var player = CreateUser("player");
        var tournament = CreateTeamTournament(organizer);
        var firstEntry = CreateEntry(0, "T-001", "Team 1");
        var secondEntry = CreateEntry(0, "T-002", "Team 2");
        tournament.Entries.Add(firstEntry);
        tournament.Entries.Add(secondEntry);
        context.AddRange(organizer, player, tournament);
        await context.SaveChangesAsync();

        context.TournamentEntryMembers.AddRange(
            CreateMember(tournament.Id, firstEntry.Id, player.Id, 1),
            CreateMember(tournament.Id, secondEntry.Id, player.Id, 1));

        await Assert.ThrowsAsync<DbUpdateException>(() => context.SaveChangesAsync());
    }

    [Fact]
    public void TournamentAndMatchVersions_AreConcurrencyTokens()
    {
        using var context = new AppDbContext(
            new DbContextOptionsBuilder<AppDbContext>().UseSqlite("Data Source=:memory:").Options);

        Assert.True(context.Model.FindEntityType(typeof(Tournament))!
            .FindProperty(nameof(Tournament.Version))!.IsConcurrencyToken);
        Assert.True(context.Model.FindEntityType(typeof(TournamentMatch))!
            .FindProperty(nameof(TournamentMatch.Version))!.IsConcurrencyToken);
        Assert.True(context.Model.FindEntityType(typeof(TournamentMatchParticipant))!
            .FindProperty(nameof(TournamentMatchParticipant.Version))!.IsConcurrencyToken);
    }

    [Fact]
    public async Task TournamentTeamBattle_CanRetainVoidedAttemptAlongsideActiveReplacement()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();
        await using var context = CreateContext(connection);
        await context.Database.EnsureCreatedAsync();

        var organizer = CreateUser("organizer");
        var tournament = CreateTeamTournament(organizer);
        var match = new TournamentMatch
        {
            Tournament = tournament,
            Bracket = TournamentBracket.Winners,
            RoundNumber = 1,
            MatchNumber = 1,
            SequenceNumber = 1,
            SideASourceKind = TournamentParticipantSourceKind.Entry,
            SideASourceReferenceId = 1,
            SideBSourceKind = TournamentParticipantSourceKind.Entry,
            SideBSourceReferenceId = 2,
            CreatedAtUtc = DateTime.UtcNow,
            UpdatedAtUtc = DateTime.UtcNow,
            Version = [1]
        };
        context.AddRange(organizer, tournament, match);
        await context.SaveChangesAsync();

        context.Battles.Add(new Battle
        {
            SourceType = BattleSourceType.TournamentTeam,
            ScoreToWin = 8,
            TournamentMatchId = match.Id,
            CreatedByUserId = organizer.Id,
            SideADesignation = BattleSide.B,
            CreatedAtUtc = DateTime.UtcNow,
            Version = [1]
        });
        await context.SaveChangesAsync();

        var battle = await context.Battles.Include(x => x.TournamentMatch).SingleAsync();
        Assert.Null(battle.PlayerAId);
        Assert.Null(battle.PlayerBId);
        Assert.Equal(match.Id, battle.TournamentMatchId);
        Assert.Equal(8, battle.ScoreToWin);

        var voidedAt = DateTime.UtcNow;
        battle.Status = BattleStatus.Voided;
        battle.TournamentMatchId = null;
        battle.TournamentMatch = null;
        battle.VoidedTournamentMatchId = match.Id;
        battle.VoidedTournamentMatch = match;
        battle.VoidedByUserId = organizer.Id;
        battle.VoidReason = "測試撤銷";
        battle.VoidSnapshot = "{\"status\":\"Completed\"}";
        battle.VoidedAtUtc = voidedAt;
        match.Battle = null;
        await context.SaveChangesAsync();
        var replacement = new Battle
        {
            SourceType = BattleSourceType.TournamentTeam,
            ScoreToWin = 8,
            TournamentMatchId = match.Id,
            CreatedByUserId = organizer.Id,
            Status = BattleStatus.Draft,
            CreatedAtUtc = DateTime.UtcNow,
            Version = [2]
        };
        context.Battles.Add(replacement);
        await context.SaveChangesAsync();

        context.ChangeTracker.Clear();
        var reloaded = await context.TournamentMatches
            .Include(x => x.Battle)
            .Include(x => x.VoidedBattles)
            .SingleAsync(x => x.Id == match.Id);
        Assert.Equal(replacement.Id, reloaded.Battle!.Id);
        var historical = Assert.Single(reloaded.VoidedBattles);
        Assert.Equal(battle.Id, historical.Id);
        Assert.Equal(BattleStatus.Voided, historical.Status);
        Assert.Equal("測試撤銷", historical.VoidReason);
        Assert.Equal("{\"status\":\"Completed\"}", historical.VoidSnapshot);
        Assert.Equal(organizer.Id, historical.VoidedByUserId);
    }

    private static AppDbContext CreatePostgreSqlContext() =>
        new(new DbContextOptionsBuilder<AppDbContext>()
            .UseNpgsql("Host=localhost;Database=beyblade;Username=beyblade")
            .Options);

    private static AppDbContext CreateContext(SqliteConnection connection) =>
        new(new DbContextOptionsBuilder<AppDbContext>().UseSqlite(connection).Options);

    private static User CreateUser(string account) => new()
    {
        Account = account,
        PasswordHash = "hash",
        DisplayName = account,
        CreatedAtUtc = DateTime.UtcNow,
        UpdatedAtUtc = DateTime.UtcNow
    };

    private static Tournament CreateIndividualTournament(User organizer) => new()
    {
        Name = "Individual Cup",
        Mode = TournamentMode.Individual,
        Format = TournamentFormat.SingleElimination,
        RegistrationMode = TournamentRegistrationMode.Individual,
        RuleSet = TournamentRuleSet.IndividualThreeBladeFourPoints,
        TeamSize = null,
        BeybladesPerPlayer = 3,
        ScoreToWin = 4,
        TargetEntryCount = 8,
        OrganizerUser = organizer,
        RulesSnapshot = "snapshot",
        CreatedAtUtc = DateTime.UtcNow,
        UpdatedAtUtc = DateTime.UtcNow,
        Version = [1]
    };

    private static Tournament CreateTeamTournament(User organizer) => new()
    {
        Name = "Team Cup",
        Mode = TournamentMode.Team,
        Format = TournamentFormat.DoubleElimination,
        RegistrationMode = TournamentRegistrationMode.CompleteTeam,
        RuleSet = TournamentRuleSet.DuoSixBladeEightPoints,
        TeamSize = 2,
        BeybladesPerPlayer = 3,
        ScoreToWin = 8,
        TargetEntryCount = 8,
        OrganizerUser = organizer,
        RulesSnapshot = "snapshot",
        CreatedAtUtc = DateTime.UtcNow,
        UpdatedAtUtc = DateTime.UtcNow,
        Version = [1]
    };

    private static TournamentEntry CreateEntry(int tournamentId, string number, string name) => new()
    {
        TournamentId = tournamentId,
        RegistrationNumber = number,
        DisplayNameSnapshot = name,
        Status = TournamentEntryStatus.Registered,
        CreatedAtUtc = DateTime.UtcNow,
        UpdatedAtUtc = DateTime.UtcNow
    };

    private static TournamentEntryMember CreateMember(int tournamentId, int entryId, int userId, int order) => new()
    {
        TournamentId = tournamentId,
        TournamentEntryId = entryId,
        UserId = userId,
        MemberOrder = order,
        DisplayNameSnapshot = $"Player {userId}",
        JoinedAtUtc = DateTime.UtcNow
    };
}
